embeddedLanguageFormatting: auto
endOfLine: lf
singleQuote: true
semi: true
tabWidth: 2
trailingComma: es5
useTabs: false
overrides:
  - files: '*.md'
    options:
      proseWrap: always
      printWidth: 80
      parser: markdown
      cursorOffset: -1
  - files: 'invokeai/frontend/public/locales/*.json'
    options:
      tabWidth: 4
