trigger:
- main

pool:
  vmImage: macOS-12

steps:
- script: |
    conda env create -f environment-mac.yml
    conda activate invokeai
    python scripts/invoke.py \
      --from_file tests/preflight_prompts.txt
  env:
    CONDA_SUBDIR: 'osx-64'
    PIP_EXISTS_ACTION: 'w'
    PYTORCH_ENABLE_MPS_FALLBACK: '1'
  displayName: 'Create and test Conda Env'
