site_name: My Docs

nav:
  - Home: 'index.md'
  - Install: 'Install/How_to_Install_InvokeAI.md'
  - Tutorials: 'Tutorials/Tutorials.md'
  - HowTo:
      - Overview: 'howto/index_old.md'
      - New to InvokeAI?: 'help/gettingStartedWithAI.md'
      - Prompting Features: 'howto/PROMPTS.md'
      - Unified Canvas: 'howto/UNIFIED_CANVAS.md'
      - Database: 'howto/DATABASE.md'
      - Control Adapters: 'howto/CONTROLNET.md'
      - Image-to-Image: 'howto/IMG2IMG.md'
      - Controlling Logging: 'howto/LOGGING.md'
      - LoRAs & LCM-LoRAs: 'howto/LORAS.md'
      - Model Merging: 'howto/MODEL_MERGING.md'
      - Workflows &  Nodes: 'nodes/overview'
      - Configuration: 'howto/CONFIGURATION.md'
      - NSFW Checker: 'howto/WATERMARK+NSFW.md'
      - Postprocessing: 'howto/POSTPROCESS.md'
      - Textual Inversions: 'howto/TEXTUAL_INVERSIONS.md'
      - Textual Inversion Training: 'howto/TRAINING.md'
      - InvokeAI Web Server: 'howto/WEB.md'
      - WebUI Hotkeys: 'howto/WEBUIHOTKEYS.md'
      - Maintenance Utilities: 'howto/UTILITIES.md'
      - Other: 'howto/OTHER.md'
      - Community Nodes: 'nodes/communityNodes.md'
      - Sampler Convergence: 'help/SAMPLER_CONVERGENCE.md'
  - Contribute:
      - How to Contribute: 'contributing/CONTRIBUTING.md'
      - InvokeAI Code of Conduct: 'CODE_OF_CONDUCT.md'
  - Development:
      - Overview: 'contributing/contribution_guides/development.md'
      - New Contributors: 'contributing/contribution_guides/newContributorChecklist.md'
      - Model Manager v2: 'contributing/MODEL_MANAGER.md'
      - Frontend Documentation: 'contributing/contribution_guides/contributingToFrontend.md'
      - Local Development: 'contributing/LOCAL_DEVELOPMENT.md'
      - Testing: 'contributing/TESTS.md'
      - Development Overview: 'contributing/frontend/OVERVIEW.md'
      - State Management: 'contributing/frontend/STATE_MGMT.md'
      - Frontend Workflows: 'contributing/frontend/WORKFLOWS.md'
      - Docs to Write: 'contributing/contribution_guides/documentation.md'
      - Nodes: 'contributing/INVOCATIONS.md'
      - Model Manager: 'contributing/MODEL_MANAGER.md'
      - Download Queue: 'contributing/DOWNLOAD_QUEUE.md'
      - Translation: 'contributing/contribution_guides/translation.md'
      - Tutorials: 'contributing/contribution_guides/tutorials.md'
  - Help Me:
      - FAQ: 'help/FAQ.md'
  - Kudos:
      - Contributors: 'other/CONTRIBUTORS.md'
