[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=43.0.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["configs*","invokeai","ldm*","backend*","scripts*"]

[project]
name = "invokeai"
version = "2.2.4"
description = "An implementation of Stable Diffusion which provides various new features and options to aid the image generation process"
readme = "README.md"
requires-python = ">=3.9, <3.11"
license = {file = "LICENSE"}
authors = [{name = "The InvokeAI Project", email = "lincoln.stein@gmail.com"}]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: GPU",
  "Environment :: GPU :: NVIDIA CUDA",
  "Environment :: MacOS X",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Artistic Software",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Server",
  "Topic :: Multimedia :: Graphics",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Image Processing",
]
dependencies = [
  "albumentations",
  "diffusers[torch]==0.10.*",
  "einops",
  "eventlet",
  "facexlib",
  "flask==2.1.3",
  "flask_cors==3.0.10",
  "flask_socketio==5.3.0",
  "flaskwebgui==1.0.3",
  "getpass_asterisk",
  "gfpgan",
  "imageio-ffmpeg",
  "kornia",
  "numpy==1.23.*",
  "omegaconf",
  "opencv-python",
  "picklescan",
  "pillow",
  "pudb",
  "pyreadline3",
  "pytorch-lightning<1.8.0",
  "realesrgan",
  "requests==2.25.1",
  "scikit-image>=0.19",
  "send2trash",
  "streamlit",
  "taming-transformers-rom1504",
  "test-tube>=0.7.5",
  "torch",
  "torch-fidelity",
  "torchvision",
  "torchmetrics",
  "transformers==4.25.*",
  "clip @ https://github.com/openai/CLIP/archive/eaa22acb90a5876642d0507623e859909230a52d.zip",
  "clipseg @ https://github.com/invoke-ai/clipseg/archive/relaxed-python-requirement.zip",
  "k-diffusion @ https://github.com/Birch-san/k-diffusion/archive/refs/heads/mps.zip",
  "pypatchmatch @ https://github.com/mauwii/PyPatchMatch/archive/refs/heads/master.zip",
]

[project.optional-dependencies]
train = [
  "accelerate"
]
mps = [
  "grpcio@https://github.com/pietrodn/grpcio-mac-arm-build/releases/download/1.51.1/grpcio-1.51.1-cp39-cp39-macosx_11_0_arm64.whl"
]

[project.scripts]
invokeai = "ldm.invoke.CLI:main"
# invokeai = "scripts.invoke:main"
configure_invokeai = "scripts.configure_invokeai:main"
create_root = "scripts.create_root:main"

[project.urls]
"Documentation" = "https://invoke-ai.github.io/InvokeAI/"
"Source" = "https://github.com/invoke-ai/InvokeAI/"
"Bug Reports" = "https://github.com/invoke-ai/InvokeAI/issues"
"Discord" = "https://discord.gg/ZmtBAhwWhy"
