[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
  "backend*",
  "configs*",
  "invokeai",
  "ldm*",
  "scripts*",
  "vendored*"
]

[tool.setuptools.package-data]
"vendored.clip.clip" = ["*.txt.gz"]

[project]
name = "invokeai"
version = "2.2.4.2"
description = "An implementation of Stable Diffusion which provides various new features and options to aid the image generation process"
readme = "README.md"
requires-python = ">=3.9, <3.11"
license = {file = "LICENSE"}
authors = [{name = "The InvokeAI Project", email = "lincoln.stein@gmail.com"}]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: GPU",
  "Environment :: GPU :: NVIDIA CUDA",
  "Environment :: MacOS X",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Artistic Software",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Server",
  "Topic :: Multimedia :: Graphics",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Image Processing",
]
# dynamic = ["dependencies"]
# [tool.setuptools.dynamic]
# dependencies = {file = ["environments-and-requirements/requirements-base.txt"]}

dependencies = [
  "albumentations",
  "diffusers[torch]==0.10.*",
  "einops",
  "eventlet",
  "facexlib",
  "flask==2.1.3",
  "flask_cors==3.0.10",
  "flask_socketio==5.3.0",
  "flaskwebgui==1.0.3",
  "getpass_asterisk",
  "gfpgan",
  "imageio-ffmpeg",
  "kornia",
  "numpy==1.23.*",
  "omegaconf",
  "opencv-python",
  "picklescan",
  "pillow",
  "pudb",
  "pyreadline3",
  "pytorch-lightning<1.8.0",
  "realesrgan",
  "requests==2.25.1",
  "scikit-image>=0.19",
  "send2trash",
  "streamlit",
  "taming-transformers-rom1504",
  "test-tube>=0.7.5",
  "torch",
  "torch-fidelity",
  "torchvision",
  "torchmetrics",
  "transformers==4.25.1",
  "k-diffusion",
  "pypatchmatch ",
]

[project.optional-dependencies]
train = [
  "accelerate"
]

[project.scripts]
invokeai = "ldm.invoke.CLI:main"
# invokeai = "scripts.invoke:main"
configure_invokeai = "scripts.configure_invokeai:main"
create_root = "scripts.create_root:main"

[project.urls]
"Documentation" = "https://invoke-ai.github.io/InvokeAI/"
"Source" = "https://github.com/invoke-ai/InvokeAI/"
"Bug Reports" = "https://github.com/invoke-ai/InvokeAI/issues"
"Discord" = "https://discord.gg/ZmtBAhwWhy"
