repo_id: "black-forest-labs/FLUX.1-schnell"
repo_path: "ae.safetensors"
params:
  resolution: 256
  in_channels: 3
  ch: 128
  out_ch: 3
  ch_mult:
  - 1
  - 2
  - 4
  - 4
  num_res_blocks: 2
  z_channels: 16
  scale_factor: 0.3611
  shift_factor: 0.1159