name: invokeai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=22.2.2
  - numpy=1.23.3
  - pip:
    - --extra-index-url  https://download.pytorch.org/whl/rocm5.2/
    - .
