name: invokeai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pip>=22.2.2
  - numpy=1.23.3
  - torchvision
  - pytorch
  - pytorch-cuda=11.6
  - pip:
    - .
