on:
  pull_request:
  push:
    branches:
      - main
      - development
      - 'release-candidate-*'

env:
  RUN_WORKFLOWS: ${{ secrets.RUN_WORKFLOWS }}

jobs:
  pyflakes:
    name: runner / pyflakes
    if: github.event.pull_request.draft == false && env.RUN_WORKFLOWS != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pyflakes
        uses: reviewdog/action-pyflakes@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
