name: Test Invoke with Conda
on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'update-gh-actions'

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: Test invoke.py on ${{ matrix.os }} with conda
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        # with:
        #   update-conda: true
        #   conda-channels: anaconda, conda-forge, pytorch

      - name: Set platform variables
        id: vars
        run: |
          [[ "$RUNNER_OS" == "macOS" ]] \
            && echo "CONDA_ENV_FILE=environment-mac.yml" >> $GITHUB_OUTPUT
          [[ "$RUNNER_OS" == "Linux" ]] \
            && echo "CONDA_ENV_FILE=environment.yml" >> $GITHUB_OUTPUT
          [[ "$GITHUB_REF" == 'refs/heads/main' ]] \
            && echo "TEST_PROMPTS=tests/preflight_prompts.txt" >> $GITHUB_OUTPUT \
            || echo "TEST_PROMPTS=tests/dev_prompts.txt" >> $GITHUB_OUTPUT
          echo "CONDA_ROOT=$CONDA" >> $GITHUB_OUTPUT

      - name: Use Cached Stable Diffusion v1.4 Model
        id: cache-sd-v1-4
        uses: actions/cache@v3
        env:
          cache-name: cache-sd-v1-4
        with:
          path: models/ldm/stable-diffusion-v1/model.ckpt
          key: ${{ env.cache-name }}
          restore-keys: |
            ${{ env.cache-name }}

      - name: Download Stable Diffusion v1.4 Model
        if: ${{ steps.cache-sd-v1-4.outputs.cache-hit != 'true' }}
        run: |
          [[ -e models/ldm/stable-diffusion-v1 ]] \
            || mkdir -p models/ldm/stable-diffusion-v1
          [[ -e models/ldm/stable-diffusion-v1/model.ckpt ]] \
            || curl -o models/ldm/stable-diffusion-v1/model.ckpt ${{ secrets.SD_V1_4_URL }}

      - name: Use Cached Dependencies
        id: cache-conda-env-invokeai
        uses: actions/cache@v3
        env:
          cache-name: cache-conda-env-invokeai
          conda-root: ${{ steps.vars.outputs.CONDA_ROOT }}
        with:
          path: ${{ env.conda-root }}/envs/invokeai
          key: ${{ env.cache-name }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles(steps.vars.outputs.CONDA_ENV_FILE) }}

      - name: update conda env
        if: ${{ steps.cache-conda-env-invokeai.outputs.cache-hit == 'true' }}
        run: |
          conda env update \
            --file ${{ steps.vars.outputs.CONDA_ENV_FILE }}

      - name: create conda env
        if: ${{ steps.cache-conda-env-invokeai.outputs.cache-hit != 'true' }}
        run: |
          conda env create \
            --file ${{ steps.vars.outputs.CONDA_ENV_FILE }} \
          || echo "temporary ignoring this error"

      - name: run preload_models.py
        run: $CONDA/envs/invokeai/bin/python scripts/preload_models.py

      - name: Run the tests
        run: |
          [[ "$RUNNER_OS" == "macOS" ]] \
            && export PYTORCH_ENABLE_MPS_FALLBACK=1
          time $CONDA/envs/invokeai/bin/python scripts/invoke.py \
            --from_file ${{ steps.vars.outputs.TEST_PROMPTS }}
          mkdir -p outputs/img-samples

      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ runner.os }}
          path: outputs/img-samples
